var ImageDataList = [
    {
        ImageID: "Hoofdweg",
        Coordinates1: "20,170,125,230",
        Coordinates2: "670,215,735,260",
        Coordinates3: null,
        Destination1: "Pad naar Hoofdingang",
        Destination2: "",
        Destination3: null,
        Task: null,
    },
    {
        ImageID: "Pad naar Hoofdingang",
        Coordinates1: "340,255,410,310",
        Coordinates2: "230,500,550,575",
        Coordinates3: null,
        Destination1: "Hoofdingang",
        Destination2: "Hoofdweg",
        Destination3: null,
        Task: null,
    },
    {
        ImageID: "Hoofdingang",
        Coordinates1: "390,220,455,290",
        Coordinates2: "250,520,525,575",
        Coordinates3: null,
        Destination1: "",
        Destination2: "Pad naar Hoofdingang",
        Destination3: null,
        Task: null,
    },
]
var TaskList = [
    {
        TaskID: "Rekenen",
        TaskQuestion: "",
        TaskAnwser: "",
    },
]